### ISSUE TITLE
Exception has occurred: ClientIDError Client ID is invalid

### ISSUE THREAD

**Issue by Omena0** [TenType/discord-rich-presence#8]
Client id (application id) is not invalid
![image](https://github.com/user-attachments/assets/c8515209-21eb-4af5-b7f3-4716eeabc17d)
![image](https://github.com/user-attachments/assets/7f4f2ce8-5291-4a11-9089-99b23a4bf36c)
![image](https://github.com/user-attachments/assets/44e38683-46a0-46a7-9ea2-593324efde65)

**Comment by TenType** [comment]
You need to put quotes around your client ID to make it a string - see [this file](https://github.com/TenType/discord-rich-presence/blob/main/examples/simple.py) for an example
